name: second_test_softcent
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  animated_bottom_navigation_bar: ^0.3.2
  circular_reveal_animation: ^2.0.0
  auto_size_text: ^3.0.0
  http: ^0.13.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/png/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DM_Sans/DMSans-Bold.ttf
        - asset: assets/fonts/DM_Sans/DMSans-Medium.ttf
        - asset: assets/fonts/DM_Sans/DMSans-Regular.ttf


